import '../models/candidate.dart';

/// Los 10 candidatos de la base de datos proporcionada por Liverpool,
/// más los campos de Puerta Liverpool: vacante, etapa, puntaje AIRA y feedback por etapa.
///
/// Distribución de la demo en el pipeline:
/// - Etapa 5 (Selección): Ana, Sofia y Carlos (los 3 con historial de entrevistas).
/// - Etapa 3 (Búsqueda): Fernanda, David y Mariana.
/// - Etapa 1 (Requisición): Javier, Laura, Ricardo y Oscar.
const seedCandidates = <Candidate>[
  Candidate(
    id: '1',
    nombre: 'Ana López',
    puestoActual: 'Gerente de Proyectos E-commerce',
    empresaActual: 'Retail Digital S.A.',
    resumenProfesional:
        'Gerente de Proyectos con 8 años de experiencia liderando la implementación de plataformas de e-commerce y optimizando la experiencia de usuario. Experta en metodologías ágiles y gestión de equipos multidisciplinarios.',
    cvPath: '/cvs/ana_lopez.pdf',
    compensacionActual: 1000000,
    compensacionDeseada: 1200000,
    escolaridad: 'Licenciatura en Marketing Digital',
    otrosEstudios: 'Certificación PMP, Diplomado en UX/UI',
    idiomas: 'Inglés (C1), Español (Nativo)',
    assessFirst: AssessFirst(
      compatibilidad: 92,
      descripcion:
          'Perfil orientado a resultados, con altas capacidades de liderazgo y visión estratégica. Excelente para roles de gestión.',
      fortalezas: 'Liderazgo, Planificación estratégica, Comunicación efectiva.',
      areasOportunidad: 'Profundizar en análisis de datos técnicos.',
      estiloLiderazgo: 'Transformacional',
      visionEstrategica: 'Alta',
      tomaDecisiones: 'Basada en datos y experiencia.',
      recomendaciones: 'Altamente recomendada para liderar proyectos de alto impacto.',
    ),
    status: CandidateStatus.finalista,
    statusJustificacion:
        'Candidata con la mejor combinación de experiencia técnica y habilidades de liderazgo. Fuerte alineación cultural.',
    vacanteId: 'v1',
    etapaActual: 5,
    airaScore: 94,
    diasEnProceso: 31,
    fotoUrl: 'assets/fotos/ana_lopez.jpg',
    contacto: ContactInfo(
      telefono: '+52 55 4180 2231',
      email: 'ana.lopez@example.com',
      linkedin: 'linkedin.com/in/ana-lopez-demo',
      ciudad: 'Ciudad de México',
    ),
    feedbackPorEtapa: {
      1: StageFeedback(
        autor: 'Mayra Cuandon',
        rol: 'HRBP',
        nota: 'Perfil registrado en la requisición. Dentro de banda salarial.',
        veredicto: Verdict.aprobado,
        fecha: '2024-09-10',
      ),
      2: StageFeedback(
        autor: 'Mariana Ortega y Aileen Vargas',
        rol: 'AT y Hiring Manager',
        nota: 'Perfil alineado: liderazgo de proyectos digitales y experiencia en e-commerce.',
        veredicto: Verdict.aprobado,
        fecha: '2024-09-14',
      ),
      3: StageFeedback(
        autor: 'Mariana Ortega',
        rol: 'Reclutadora',
        nota: 'Perfil sólido, 8 años en e-commerce y certificación PMP. AIRA la coloca en el top 1.',
        veredicto: Verdict.recomendado,
        fecha: '2024-09-20',
      ),
      4: StageFeedback(
        autor: 'Sofia Rodriguez',
        rol: 'Líder Técnico',
        nota:
            'Sólido conocimiento técnico en plataformas e-commerce. Respondió con seguridad a preguntas sobre arquitectura de sistemas.',
        veredicto: Verdict.recomendado,
        fecha: '2024-09-28',
      ),
      5: StageFeedback(
        autor: 'Carlos Sanchez y Aileen Vargas',
        rol: 'Director de Marketing y Hiring Manager',
        nota:
            "Excelente visión de negocio y enfoque en el cliente. Presentó casos de éxito relevantes. Aileen Vargas: 'Su experiencia en optimización de conversión es justo lo que buscamos'.",
        veredicto: Verdict.recomendado,
        fecha: '2024-10-05',
      ),
    },
  ),
  Candidate(
    id: '2',
    nombre: 'Carlos Mendoza',
    puestoActual: 'Desarrollador Backend Senior',
    empresaActual: 'Soluciones Tech S. de R.L.',
    resumenProfesional:
        'Desarrollador Backend con 6 años de experiencia en la construcción de APIs RESTful y microservicios con Java y Spring Boot. Apasionado por el código limpio y las buenas prácticas de desarrollo.',
    cvPath: '/cvs/carlos_mendoza.pdf',
    compensacionActual: 850000,
    compensacionDeseada: 950000,
    escolaridad: 'Ingeniería en Sistemas Computacionales',
    otrosEstudios: 'Certificación AWS Certified Developer',
    idiomas: 'Inglés (B2), Español (Nativo)',
    assessFirst: AssessFirst(
      compatibilidad: 88,
      descripcion:
          'Perfil técnico robusto, con gran capacidad de análisis y resolución de problemas. Colaborador y proactivo.',
      fortalezas: 'Resolución de problemas, Lógica de programación, Trabajo en equipo.',
      areasOportunidad: 'Desarrollar habilidades de mentoría.',
      estiloLiderazgo: 'N/A (Colaborador individual)',
      visionEstrategica: 'Media',
      tomaDecisiones: 'Analítica y metódica.',
      recomendaciones: 'Recomendado para roles Senior que requieran alta capacidad técnica.',
    ),
    status: CandidateStatus.descartado,
    statusJustificacion:
        'Aunque es técnicamente muy sólido, buscamos un perfil con más experiencia en liderazgo de equipos para la posición actual.',
    vacanteId: 'v1',
    etapaActual: 5,
    airaScore: 81,
    diasEnProceso: 30,
    fotoUrl: 'assets/fotos/carlos_mendoza.jpg',
    contacto: ContactInfo(
      telefono: '+52 33 3920 7714',
      email: 'carlos.mendoza@example.com',
      linkedin: 'linkedin.com/in/carlos-mendoza-demo',
      github: 'github.com/carlos-mendoza-demo',
      ciudad: 'Guadalajara',
    ),
    feedbackPorEtapa: {
      3: StageFeedback(
        autor: 'Mariana Ortega',
        rol: 'Reclutadora',
        nota: 'Técnicamente muy fuerte. Validar experiencia liderando proyectos.',
        veredicto: Verdict.recomendado,
        fecha: '2024-09-21',
      ),
      4: StageFeedback(
        autor: 'Sofia Rodriguez',
        rol: 'Líder Técnico',
        nota:
            'Dominio excepcional de Spring Boot y microservicios. Resolvió el reto técnico en tiempo récord. Muy buen fit técnico.',
        veredicto: Verdict.recomendado,
        fecha: '2024-09-29',
      ),
      5: StageFeedback(
        autor: 'Aileen Vargas',
        rol: 'Hiring Manager',
        nota:
            'Gran actitud y habilidades técnicas. Sin embargo, en la conversación sobre liderazgo de proyectos, mostró menos experiencia de la requerida.',
        veredicto: Verdict.noRecomendado,
        fecha: '2024-10-06',
      ),
    },
  ),
  Candidate(
    id: '3',
    nombre: 'Sofia Herrera',
    puestoActual: 'Analista de Datos Jr.',
    empresaActual: 'Consultoría Analítica Co.',
    resumenProfesional:
        'Analista de Datos con 2 años de experiencia en la extracción y visualización de datos para la toma de decisiones. Experiencia con SQL, Python (Pandas) y Tableau.',
    cvPath: '/cvs/sofia_herrera.pdf',
    compensacionActual: 500000,
    compensacionDeseada: 600000,
    escolaridad: 'Actuaría',
    otrosEstudios: 'Curso intensivo de Ciencia de Datos',
    idiomas: 'Inglés (C1), Español (Nativo)',
    assessFirst: AssessFirst(
      compatibilidad: 95,
      descripcion:
          'Perfil con alto potencial, muy analítica y con una gran curiosidad intelectual. Rápido aprendizaje y alta motivación.',
      fortalezas: 'Análisis numérico, Curiosidad, Atención al detalle.',
      areasOportunidad: 'Experiencia en proyectos de gran escala.',
      estiloLiderazgo: 'N/A',
      visionEstrategica: 'Baja (en desarrollo)',
      tomaDecisiones: 'Basada en evidencia y datos.',
      recomendaciones: 'Excelente candidata para una posición de entrada con alto potencial de crecimiento.',
    ),
    status: CandidateStatus.enProceso,
    statusJustificacion: '',
    vacanteId: 'v1',
    etapaActual: 5,
    airaScore: 90,
    diasEnProceso: 28,
    fotoUrl: 'assets/fotos/sofia_herrera.jpg',
    contacto: ContactInfo(
      telefono: '+52 55 6012 4478',
      email: 'sofia.herrera@example.com',
      linkedin: 'linkedin.com/in/sofia-herrera-demo',
      github: 'github.com/sofia-herrera-demo',
      ciudad: 'Ciudad de México',
    ),
    feedbackPorEtapa: {
      3: StageFeedback(
        autor: 'Mariana Ortega',
        rol: 'Reclutadora',
        nota: 'Alto potencial. SQL, Python y Tableau. AssessFirst 95 %.',
        veredicto: Verdict.recomendado,
        fecha: '2024-09-24',
      ),
      4: StageFeedback(
        autor: 'Juan Perez',
        rol: 'Gerente de BI',
        nota:
            'Conocimientos sólidos en SQL y Tableau. Demostró gran capacidad para interpretar datos y comunicar hallazgos. Potencial a desarrollar.',
        veredicto: Verdict.recomendado,
        fecha: '2024-10-01',
      ),
      5: StageFeedback(
        autor: 'Aileen Vargas',
        rol: 'Hiring Manager',
        nota:
            'Muy entusiasta y con ganas de aprender. Se alinea bien con la cultura del equipo. Pendiente de la entrevista final con el director del área.',
        veredicto: Verdict.recomendado,
        fecha: '2024-10-08',
      ),
    },
  ),
  Candidate(
    id: '4',
    nombre: 'Javier Torres',
    puestoActual: 'Diseñador UX/UI Senior',
    empresaActual: 'Creativos App Factory',
    resumenProfesional:
        'Diseñador UX/UI con más de 7 años de experiencia en la creación de interfaces intuitivas para aplicaciones móviles y web. Experto en Figma, Sketch y Adobe XD.',
    cvPath: '/cvs/javier_torres.pdf',
    compensacionActual: 900000,
    compensacionDeseada: 1050000,
    escolaridad: 'Licenciatura en Diseño Gráfico',
    otrosEstudios: 'Certificación en Interacción Humano-Computadora',
    idiomas: 'Inglés (C1), Español (Nativo)',
    assessFirst: AssessFirst(
      compatibilidad: 85,
      descripcion: 'Creativo y enfocado en el usuario.',
      fortalezas: 'Creatividad, Empatía',
      areasOportunidad: 'Gestión de proyectos',
      recomendaciones: 'Fuerte para roles de diseño senior.',
    ),
    status: CandidateStatus.enProceso,
    statusJustificacion: '',
    vacanteId: 'v1',
    etapaActual: 1,
    airaScore: 74,
    diasEnProceso: 4,
    fotoUrl: 'assets/fotos/javier_torres.png',
    contacto: ContactInfo(
      telefono: '+52 81 8345 1190',
      email: 'javier.torres@example.com',
      linkedin: 'linkedin.com/in/javier-torres-demo',
      portafolio: 'behance.net/javier-torres-demo',
      ciudad: 'Monterrey',
    ),
  ),
  Candidate(
    id: '5',
    nombre: 'Laura Jimenez',
    puestoActual: 'Especialista en Marketing Digital',
    empresaActual: 'Agencia Impacto Online',
    resumenProfesional:
        'Especialista en Marketing Digital con 4 años de experiencia en campañas de SEO/SEM, redes sociales y email marketing.',
    cvPath: '/cvs/laura_jimenez.pdf',
    compensacionActual: 650000,
    compensacionDeseada: 750000,
    escolaridad: 'Licenciatura en Comunicación',
    otrosEstudios: 'Certificación Google Ads',
    idiomas: 'Inglés (B2), Español (Nativo)',
    assessFirst: AssessFirst(
      compatibilidad: 89,
      descripcion: 'Orientada a resultados, proactiva.',
      fortalezas: 'Análisis de métricas, Creatividad',
      areasOportunidad: 'Liderazgo de equipos',
      recomendaciones: 'Buen fit para roles de ejecución de campañas.',
    ),
    status: CandidateStatus.enProceso,
    statusJustificacion: '',
    vacanteId: 'v1',
    etapaActual: 1,
    airaScore: 72,
    diasEnProceso: 3,
    fotoUrl: 'assets/fotos/laura_jimenez.jpg',
    contacto: ContactInfo(
      telefono: '+52 55 2987 6601',
      email: 'laura.jimenez@example.com',
      linkedin: 'linkedin.com/in/laura-jimenez-demo',
      ciudad: 'Ciudad de México',
    ),
  ),
  Candidate(
    id: '6',
    nombre: 'David Peña',
    puestoActual: 'Arquitecto de Soluciones Cloud',
    empresaActual: 'Nube Segura Inc.',
    resumenProfesional:
        'Arquitecto Cloud con 10 años de experiencia diseñando e implementando soluciones escalables y seguras en AWS y Azure.',
    cvPath: '/cvs/david_pena.pdf',
    compensacionActual: 1500000,
    compensacionDeseada: 1700000,
    escolaridad: 'Ingeniería en Telemática',
    otrosEstudios: 'Certificaciones AWS Solutions Architect Professional y Azure Solutions Architect Expert',
    idiomas: 'Inglés (C2), Español (Nativo)',
    assessFirst: AssessFirst(
      compatibilidad: 91,
      descripcion: 'Visión estratégica y profundo conocimiento técnico.',
      fortalezas: 'Arquitectura de sistemas, Seguridad',
      areasOportunidad: 'Gestión de presupuesto',
      recomendaciones: 'Candidato ideal para roles de arquitectura de alto nivel.',
    ),
    status: CandidateStatus.descartado,
    statusJustificacion: 'Las expectativas salariales exceden el presupuesto para la vacante.',
    vacanteId: 'v1',
    etapaActual: 3,
    airaScore: 79,
    diasEnProceso: 17,
    contacto: ContactInfo(
      telefono: '+52 55 7143 3382',
      email: 'david.pena@example.com',
      linkedin: 'linkedin.com/in/david-pena-demo',
      github: 'github.com/david-pena-demo',
      ciudad: 'Querétaro',
    ),
    feedbackPorEtapa: {
      3: StageFeedback(
        autor: 'Mariana Ortega',
        rol: 'Reclutadora',
        nota: 'Perfil excelente, pero su compensación deseada (\$1.7M) está fuera de la banda (\$1.3M).',
        veredicto: Verdict.noRecomendado,
        fecha: '2024-09-25',
      ),
    },
  ),
  Candidate(
    id: '7',
    nombre: 'Fernanda Morales',
    puestoActual: 'Scrum Master',
    empresaActual: 'Agile Development Corp.',
    resumenProfesional:
        'Scrum Master certificada con 5 años de experiencia facilitando ceremonias ágiles y removiendo impedimentos para equipos de desarrollo.',
    cvPath: '/cvs/fernanda_morales.pdf',
    compensacionActual: 750000,
    compensacionDeseada: 850000,
    escolaridad: 'Licenciatura en Administración de Empresas',
    otrosEstudios: 'Certified ScrumMaster (CSM), SAFe Agilist',
    idiomas: 'Inglés (C1), Español (Nativo)',
    assessFirst: AssessFirst(
      compatibilidad: 93,
      descripcion: 'Facilitadora natural, excelentes habilidades de comunicación.',
      fortalezas: 'Comunicación, Resolución de conflictos',
      areasOportunidad: 'Conocimiento técnico profundo',
      recomendaciones: 'Recomendada para mejorar la agilidad de los equipos.',
    ),
    status: CandidateStatus.enProceso,
    statusJustificacion: '',
    vacanteId: 'v1',
    etapaActual: 3,
    airaScore: 88,
    diasEnProceso: 18,
    fotoUrl: 'assets/fotos/fernanda_morales.jpg',
    contacto: ContactInfo(
      telefono: '+52 55 3321 9045',
      email: 'fernanda.morales@example.com',
      linkedin: 'linkedin.com/in/fernanda-morales-demo',
      ciudad: 'Ciudad de México',
    ),
    feedbackPorEtapa: {
      3: StageFeedback(
        autor: 'Mariana Ortega',
        rol: 'Reclutadora',
        nota: 'CSM y SAFe, 5 años facilitando equipos. Buena candidata para pasar con el HM.',
        veredicto: Verdict.recomendado,
        fecha: '2024-09-26',
      ),
    },
  ),
  Candidate(
    id: '8',
    nombre: 'Ricardo Salas',
    puestoActual: 'Desarrollador Frontend',
    empresaActual: 'Innovación Web',
    resumenProfesional:
        'Desarrollador Frontend con 3 años de experiencia construyendo interfaces de usuario responsivas con React y TypeScript.',
    cvPath: '/cvs/ricardo_salas.pdf',
    compensacionActual: 600000,
    compensacionDeseada: 700000,
    escolaridad: 'Ingeniería en Tecnologías de la Información',
    otrosEstudios: 'Cursos avanzados de React en Platzi',
    idiomas: 'Inglés (B2), Español (Nativo)',
    assessFirst: AssessFirst(
      compatibilidad: 87,
      descripcion: 'Apasionado por la tecnología y la experiencia de usuario.',
      fortalezas: 'React, CSS, Trabajo en equipo',
      areasOportunidad: 'Automatización de pruebas',
      recomendaciones: 'Buen candidato para un equipo de desarrollo frontend.',
    ),
    status: CandidateStatus.enProceso,
    statusJustificacion: '',
    vacanteId: 'v1',
    etapaActual: 1,
    airaScore: 68,
    diasEnProceso: 3,
    fotoUrl: 'assets/fotos/ricardo_salas.jpg',
    contacto: ContactInfo(
      telefono: '+52 222 614 5507',
      email: 'ricardo.salas@example.com',
      linkedin: 'linkedin.com/in/ricardo-salas-demo',
      github: 'github.com/ricardo-salas-demo',
      portafolio: 'ricardo-salas-demo.dev',
      ciudad: 'Puebla',
    ),
  ),
  Candidate(
    id: '9',
    nombre: 'Mariana Castillo',
    puestoActual: 'HR Business Partner',
    empresaActual: 'Talento Humano Global',
    resumenProfesional:
        'HRBP con 6 años de experiencia gestionando el ciclo de vida del empleado, relaciones laborales y desarrollo organizacional.',
    cvPath: '/cvs/mariana_castillo.pdf',
    compensacionActual: 800000,
    compensacionDeseada: 900000,
    escolaridad: 'Licenciatura en Psicología Organizacional',
    otrosEstudios: 'Maestría en Desarrollo Humano',
    idiomas: 'Inglés (C1), Español (Nativo)',
    assessFirst: AssessFirst(
      compatibilidad: 90,
      descripcion: 'Empática, estratégica y con fuerte enfoque en el negocio.',
      fortalezas: 'Relaciones laborales, Comunicación',
      areasOportunidad: 'Análisis de datos de RH',
      recomendaciones: 'Fuerte candidata para una posición de HRBP.',
    ),
    status: CandidateStatus.descartado,
    statusJustificacion: 'Se decidió por un candidato interno.',
    vacanteId: 'v1',
    etapaActual: 3,
    airaScore: 76,
    diasEnProceso: 16,
    fotoUrl: 'assets/fotos/mariana_castillo.jpg',
    contacto: ContactInfo(
      telefono: '+52 55 8856 1273',
      email: 'mariana.castillo@example.com',
      linkedin: 'linkedin.com/in/mariana-castillo-demo',
      ciudad: 'Ciudad de México',
    ),
    feedbackPorEtapa: {
      3: StageFeedback(
        autor: 'Mariana Ortega',
        rol: 'Reclutadora',
        nota: 'Buen perfil de negocio. Se decidió avanzar con un candidato interno.',
        veredicto: Verdict.noRecomendado,
        fecha: '2024-09-27',
      ),
    },
  ),
  Candidate(
    id: '10',
    nombre: 'Oscar Paredes',
    puestoActual: 'Becario de Calidad de Software',
    empresaActual: 'Pruebas Perfectas Ltda.',
    resumenProfesional:
        'Estudiante de último semestre de Ingeniería de Software buscando experiencia en el área de QA. Conocimientos básicos en Selenium y Cypress.',
    cvPath: '/cvs/oscar_paredes.pdf',
    compensacionActual: 100000,
    compensacionDeseada: 150000,
    escolaridad: 'Estudiante de Ingeniería de Software',
    otrosEstudios: 'Ninguno',
    idiomas: 'Inglés (B1), Español (Nativo)',
    assessFirst: AssessFirst(
      compatibilidad: 82,
      descripcion: 'Alto potencial, con ganas de aprender.',
      fortalezas: 'Atención al detalle, Lógica',
      areasOportunidad: 'Experiencia práctica',
      recomendaciones: 'Buen candidato para un programa de becarios.',
    ),
    status: CandidateStatus.enProceso,
    statusJustificacion: '',
    vacanteId: 'v1',
    etapaActual: 1,
    airaScore: 55,
    diasEnProceso: 2,
    fotoUrl: 'assets/fotos/oscar_paredes.jpg',
    contacto: ContactInfo(
      telefono: '+52 55 1409 7736',
      email: 'oscar.paredes@example.com',
      linkedin: 'linkedin.com/in/oscar-paredes-demo',
      github: 'github.com/oscar-paredes-demo',
      ciudad: 'Estado de México',
    ),
  ),
];
